chore(internal): support env vars in `./scripts/repl`

diff --git a/scripts/repl b/scripts/repl
--- a/scripts/repl
+++ b/scripts/repl
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [ -z "$BEEPER_ACCESS_TOKEN" ]; then
+  echo 'ERROR: BEEPER_ACCESS_TOKEN environment variable is required but not set'
+  exit 1
+fi
+
 echo "==> Detecting PostgreSQL Python executable"
 PYTHON_EXECUTABLE_PATH=$(pg_config --configure | grep -o "PYTHON=[^ ]*" | cut -d= -f2 | tr -d "'")
 echo "PostgreSQL uses Python $PYTHON_EXECUTABLE_PATH"
@@ -29,8 +34,8 @@ if [ "$PG_MAJOR_VERSION" -ge 18 ]; then
   done
   POSTGRES_CONFIG=(-c extension_control_path="$(realpath temp/install/share/postgresql)")
 else
-  # In PostgreSQL <18 we cannot point `postgres` to our local extensions directory. So we install directly to
-  # the system.
+  # In PostgreSQL <18 we cannot point `postgres` to our local extensions directory. So we install
+  # directly to the system.
   sudo make install PG_CONFIG="$(command -v pg_config)"
 fi
 
@@ -60,6 +65,11 @@ done
 
 echo "==> Running setup.sql"
 psql -d postgres -f test/sql/create_extension.sql
+
+psql -d postgres --variable "value='$BEEPER_ACCESS_TOKEN'" -c 'ALTER DATABASE postgres SET beeper_desktop_api.beeper_access_token = :value;'
+if [ -n "$BEEPER_DESKTOP_BASE_URL" ]; then
+  psql -d postgres --variable "value='$BEEPER_DESKTOP_BASE_URL'" -c 'ALTER DATABASE postgres SET beeper_desktop_api.base_url = :value;'
+fi
 
 if command -v pgcli &>/dev/null; then
   echo "==> Starting pgcli REPL"
